site_name: DBMS - Database Management Systems
theme: 
  name: material
  logo: assets/logocaminas.png

  palette: 
    - media: "(prefers-color-scheme: light)"    
    # Palette toggle for light mode
      scheme: default
      primary: blue
      accent: green 
      toggle:
        icon: material/weather-night
        name: Cambiar a modo oscuro

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/weather-sunny
        name: Cambiar a modo claro
  language: en
  features:
    #- navigation.sections
    - navigation.top
    #- navigation.expand
    - toc.integrate
    - search.highlight
    - content.code.annotation
    - content.code.copy

markdown_extensions:
  - meta
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - admonition
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - attr_list
  - md_in_html
  - footnotes
  
plugins: 
  - search:
      lang: en

extra_css:
  - stylesheets/extra.css

nav:
    - Eng:
      - Unit 0:
        - U0_1_Introduction.md
        - U0_2_Windows_Server_in_Azure.md
        - U0_3_Windows_Server_in_AWSAcademy.md
      - Unit 1:
        - U1_1_Introduction_to_DBMS.md
      - Unit 2:
        - U2_1_Oracle_DBMS_basics.md
        - U2_2_Oracle_installation.md
        - U2_3_Oracle_connection.md
        - U2_4_Oracle_start_and_stop.md
        - U2_5_Oracle-Basic_administration.md  

extra:
  analytics: 
      provider: google 
      property: G-3NX5MD5C8H

  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/jmunozji
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ppmunozj